### ISSUE TITLE
Nice way to bulk change themes across all pages

### ISSUE THREAD

**Issue by smiffy6969** [smiffy6969/razorCMS#25]
This is a delicate task, themes can have multiple layouts so ensuring we match new layouts with current layouts selected is a big task. If we find no match then we need to find a way to default to a certain layout. Can use the manifest details to determine layouts.

**Comment by Xarcell** [comment]
I'm not sure if this idea is helps, but I kinda like the way SMF has it. An idea would be to have a "Master" theme. If the file doesn't exist in a custom theme, then it substitutes missing files from the Master theme as the fallback. The master theme should not ever be edited, but can be copied and changed as a new custom theme, without every single file needing to be present as missing files of the custom theme are substituted from the Master theme as a fallback. This way, custom themes only change & pack the files they want to change.
