### ISSUE TITLE
Login Failure

### ISSUE THREAD

**Issue by Xarcell** [smiffy6969/razorCMS#35]
For Development Version

Trying to login doesn't seem to do anything, not even a warning that the credentials failed. I don't know what else to tell you. Let me know if you need anything. Just in case you want to sample it: http://files.xarcell-studios.com/razor-dev-test/

PHPINFO in case you want it: http://files.xarcell-studios.com/php-info.php

**Comment by smiffy6969** [comment]
please test latest master release.

ta

paul

**Comment by Xarcell** [comment]
Paul, this issue concerns the development version, not the master.

**Comment by Xarcell** [comment]
Problems solved.

**Comment by smiffy6969** [comment]
I know it does but I have released a new master version which means the dev version has been updated too, and merged to master. So testing the new 3.4.1 release means that it has been fixed on dev and pushed to master.
Sent using CloudMagic
On Tue, Jan 06, 2015 at 10:06 pm, Xarcell <notifications@github.com> wrote:Paul, this issue concerns the development version, not the master.
