### ISSUE TITLE
Disappearing Bootstrap Glyphicon

### ISSUE THREAD

**Issue by spideynn** [smiffy6969/razorCMS#37]
When editing the default home page and I press backspace, the Bootstrap leaf Glyphicon disappears. I can only get it back by pressing Control+Z.

Apache 2.4, PHP 5.5.15 on Windows 8.1, using Firefox on Windows 7 to view the site.

**Comment by smiffy6969** [comment]
To add glyph icons or font awesome icons you will need to add the HTML so switch editor to code view.....
Go to fontawesome website, look for the HTML you need to add for the icon you want and add this in code view. 
The editor needs an icon button but for noe you can do it that's way.
Sent using CloudMagic
On Sat, Feb 28, 2015 at 3:06 pm, Spideynn <notifications@github.com> wrote:When editing the default home page and I press backspace, the Bootstrap leaf Glyphicon disappears. I can only get it back by pressing Control+Z.

**Comment by spideynn** [comment]
Thanks!
