### ISSUE TITLE
Enabling HTTPS

### ISSUE THREAD

**Issue by jacobm001** [smiffy6969/razorCMS#44]
I have enabled HTTPS on my site.  Razor doesn't seem to be detecting this for some reason, which prevents my web browser from loading javascript, css, and fonts.  Am I missing a configuration setting?

**Comment by Petrouchka** [comment]
It's because there are any absolute URL in the code, with http. You must use relatives URL instead. Example :

        
        <link type="text/css" rel="stylesheet" href="extension/theme/swamper/bootswatch-spacelab/style/style.css">

**Comment by smiffy6969** [comment]
To be honest, the correct way as described above is to use relative URLs or where possible from php files use the base URL constant RAZOR_BASE_URL in php tags before your URL, this is rewritten automatically when it detacts https.

The issue can be that http is not being detected, so if using https then the base URL is not being changed.

Can you check your paths using f12 dev console to view your page in chrome or ff. Then go to the head section of the page and find all the URLs being called for stylesheets and js and see if they say http or https

**Comment by jacobm001** [comment]
The fonts section is the only one that looks like it's getting pushed to HTTPS, but I do get an error in the dev console about an HTTP font request.

![capture](https://cloud.githubusercontent.com/assets/2245023/12331710/9b4d7024-ba9f-11e5-8d60-d1227e359c2d.PNG)

**Comment by smiffy6969** [comment]
I'll have a quick look in bit. I think I know what it might be... Let me sort
kids out first ;)


Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.91&pv=6.0.1&source=email_footer_2] On Thu, Jan 14, 2016 at 5:18 p.m., Jacob < notifications@github.com [notifications@github.com] > wrote:
The fonts section is the only one that looks like it's getting pushed to HTTPS,
but I do get an error in the dev console about an HTTP font request.

capture
[https://cloud.githubusercontent.com/assets/2245023/12331710/9b4d7024-ba9f-11e5-8d60-d1227e359c2d.PNG]
[https://cloud.githubusercontent.com/assets/2245023/12331710/9b4d7024-ba9f-11e5-8d60-d1227e359c2d.PNG]

—
Reply to this email directly or view it on GitHub
[https://github.com/smiffy6969/razorCMS/issues/44#issuecomment-171711208] .[https://github.com/notifications/beacon/AHN15tenA9-LzUp_AlLEagkYUm-iDK6Aks5pZ8_VgaJpZM4HEooL.gif]

**Comment by smiffy6969** [comment]
open /index.php line 20

change

```
define("RAZOR_BASE_URL", (isset($_SERVER['https']) && !empty($_SERVER['https']) ? "https://" : "http://").$_SERVER["SERVER_NAME"].$port.str_replace(array("index.php"), "", $_SERVER["SCRIPT_NAME"]));
```

to

```
define("RAZOR_BASE_URL", (!empty($_SERVER['HTTPS']) ? "https://" : "http://").$_SERVER["SERVER_NAME"].$port.str_replace(array("index.php"), "", $_SERVER["SCRIPT_NAME"]));
```

open /rars/index.php line 16

change

```
define("RARS_BASE_URL", (isset($_SERVER['https']) && !empty($_SERVER['https']) ? "https://" : "http://").$_SERVER["SERVER_NAME"].$port.str_replace(array("index.php"), "", $_SERVER["SCRIPT_NAME"]));
```

to

```
define("RARS_BASE_URL", (!empty($_SERVER['HTTPS']) ? "https://" : "http://").$_SERVER["SERVER_NAME"].$port.str_replace(array("index.php"), "", $_SERVER["SCRIPT_NAME"]));
```

line 18 change

```
define("RAZOR_BASE_URL", (isset($_SERVER['https']) && !empty($_SERVER['https']) ? "https://" : "http://").$_SERVER["SERVER_NAME"].$port.str_replace(array("rars/index.php"), "", $_SERVER["SCRIPT_NAME"]));
```

to

```
define("RAZOR_BASE_URL", (!empty($_SERVER['HTTPS']) ? "https://" : "http://").$_SERVER["SERVER_NAME"].$port.str_replace(array("rars/index.php"), "", $_SERVER["SCRIPT_NAME"]));
```

This will properly check for https on server.... i noticed this the other day on a completely different project, and it too had https in lower case and not caps.... but i also removed unnecessary isset calls as empty check for this anyway.

Let me know if this works for you, it did for me on another project that used similar code.

ta

Paul
;)

**Comment by smiffy6969** [comment]
I will push this in a new release, but for now you can update.... new release will be a little way off as I need to change ui engine.

**Comment by jacobm001** [comment]
Thank you smiffy.

That seems to have solved the https problems. Not sure if it's related or not, but I am getting two javascript errors.

![capture](https://cloud.githubusercontent.com/assets/2245023/12335006/d8324bba-bab1-11e5-81c0-5f997e71fb83.PNG)

![capture2](https://cloud.githubusercontent.com/assets/2245023/12335058/1b20e62a-bab2-11e5-9fd6-cf889896ff05.PNG)

**Comment by smiffy6969** [comment]
What browser are you using? Looks like chrome.... Can you with dev console open, right click refresh icon and do full hard reload dumping cache.... Or press Ctrl + shift + r with dev console open.

Might be trying to load via require from cache, which will still be http, which will get blocked in https

I would assume it's that

**Comment by jacobm001** [comment]
Yes, I am using Chrome. Temporarily switching workstations... 

Doing a hard refresh solved that problem, and I get the login dialog now. If I enter the default credentials as they're listed on the downloads page of your website, I get a login loop. If I enter in some random credentials, I get a failed login notice.

So it looks like I'm able to authenticate, and I'm not getting any errors in the console, but it won't give me the razor admin console.

**Comment by smiffy6969** [comment]
You have permissions set wrong on your sqlite file you can find it in storage folder..... if you have pushed these files to a server and are not running php you need to chown all files to www-data or nobody depending on how your server setup.... I have to do this on my vps when i push files over to it as it does not run suphp.

```
sudo chown -R  www-data:YOURUSERNAME /LOC/OF/FILES
```

then i would 

```
sudo chmod -R 775 /LOC/OF/FILES
```

This will make all files for razor owned by server, but your user as the group to allow you to overwrite them easily, finally setting 775 to give owner and group write.


You will have to do this whenever you overwrite files, or you could just install suphp and not worry again ;)


The reason for the loop is because it actually logs you in, then it writes to sqlite to store last logged in, then on reload checks access again and because the last logged in is not written to db (no permissions) it logs you out again as the key fails to validate (I am a bit OTT with login scipts, better safe than sorry).

You will also find if you swap IP's mid whilst logged in, it will log you out, just heads up if using mobile with wireless turned on and you walk in the house after being on mobile data.

Also, while i am at it, change the google font url to be always https as this works fine for both instances, and also stops errors being thrown about supplying something over non secure connection.

;)

**Comment by jacobm001** [comment]
Damn it. That's an absolutely beginners mistake. I did that on the original install, messed with it, and reinstalled. Forgot to change the ownership to www-data on the reinstall.

> I am a bit OTT with login scipts, better safe than sorry

Agreed!

Thank you very much for the prompt help. It's greatly appreciated, and I've really enjoyed your work when I was experimenting with it locally. I will fix the fonts while I'm at it. :)
